const chefInfo = document.getElementById("chef-info")
const chefCard = document.getElementById("chef-card")
const chefDetailLink = document.getElementById("chef-detail-link")
const chefDesc = document.getElementById("chef-description")
chefInfo.addEventListener('mouseover', (event) =>{
  chefCard.classList.add('blur')
  chefDetailLink.classList.remove('hidden')
  chefDesc.classList.remove('hidden')
})
chefInfo.addEventListener('mouseleave', (event) =>{
  chefCard.classList.remove('blur')
  chefDetailLink.classList.add('hidden')
  chefDesc.classList.add('hidden')
})

const wildlifeInfo = document.getElementById("wildlife-info")
const wildlifeCard = document.getElementById("wildlife-card")
const wildlifeDetailLink = document.getElementById("wildlife-detail-link")
const wildlifeDesc = document.getElementById("wildlife-description")
wildlifeInfo.addEventListener('mouseover', (event) =>{
  wildlifeCard.classList.add('blur')
  wildlifeDetailLink.classList.remove('hidden')
  wildlifeDesc.classList.remove('hidden')
})
wildlifeInfo.addEventListener('mouseleave', (event) =>{
  wildlifeCard.classList.remove('blur')
  wildlifeDetailLink.classList.add('hidden')
  wildlifeDesc.classList.add('hidden')
})

const climateInfo = document.getElementById("climate-info")
const climateCard = document.getElementById("climate-card")
const climateLink = document.getElementById("climate-github-link")
const climateLink2 = document.getElementById("climate-figma-link")
const climateDesc = document.getElementById("climate-description")
climateInfo.addEventListener('mouseover', (event) =>{
  climateCard.classList.add('blur')
  climateLink.classList.remove('hidden')
  climateLink2.classList.remove('hidden')
  climateDesc.classList.remove('hidden')
})
climateInfo.addEventListener('mouseleave', (event) =>{
  climateCard.classList.remove('blur')
  climateLink.classList.add('hidden')
  climateLink2.classList.add('hidden')
  climateDesc.classList.add('hidden')
})


const ayudaInfo = document.getElementById("ayuda-info")
const ayudaCard = document.getElementById("ayuda-card")
const ayudaLink = document.getElementById("ayuda-detail-link")
// const ayudaLink = document.getElementById("ayuda-figma-link")
// const ayudaLink2 = document.getElementById("ayuda-figma-link2")
const ayudaDesc = document.getElementById("ayuda-description")
ayudaInfo.addEventListener('mouseover', (event) =>{
  ayudaCard.classList.add('blur')
  ayudaLink.classList.remove('hidden')
  // ayudaLink2.classList.remove('hidden')
  ayudaDesc.classList.remove('hidden')
})
ayudaInfo.addEventListener('mouseleave', (event) =>{
  ayudaCard.classList.remove('blur')
  ayudaLink.classList.add('hidden')
  // ayudaLink2.classList.add('hidden')
  ayudaDesc.classList.add('hidden')
})

const scrabbleInfo = document.getElementById("scrabble-info")
const scrabbleCard = document.getElementById("scrabble-card")
const scrabbleLink = document.getElementById("scrabble-github-link")
const scrabbleDesc = document.getElementById("scrabble-description")
scrabbleInfo.addEventListener('mouseover', (event) =>{
  scrabbleCard.classList.add('blur')
  scrabbleLink.classList.remove('hidden')
  scrabbleDesc.classList.remove('hidden')
})
scrabbleInfo.addEventListener('mouseleave', (event) =>{
  scrabbleCard.classList.remove('blur')
  scrabbleLink.classList.add('hidden')
  scrabbleDesc.classList.add('hidden')
})

// const gifInfo = document.getElementById("gif-info")
// const gifCard = document.getElementById("gif-card")
// const gifLink = document.getElementById("gif-github-link")
// const gifDesc = document.getElementById("gif-description")
// gifInfo.addEventListener('mouseover', (event) =>{
//   gifCard.classList.add('blur')
//   gifLink.classList.remove('hidden')
//   gifDesc.classList.remove('hidden')
// })
// gifInfo.addEventListener('mouseleave', (event) =>{
//   gifCard.classList.remove('blur')
//   gifLink.classList.add('hidden')
//   gifDesc.classList.add('hidden')
// })

// const wineInfo = document.getElementById("wine-info")
// const wineCard = document.getElementById("wine-card")
// const wineLink = document.getElementById("wine-github-link")
// const wineDesc = document.getElementById("wine-description")
// wineInfo.addEventListener('mouseover', (event) =>{
//   wineCard.classList.add('blur')
//   wineLink.classList.remove('hidden')
//   wineDesc.classList.remove('hidden')
// })
// wineInfo.addEventListener('mouseleave', (event) =>{
//   wineCard.classList.remove('blur')
//   wineLink.classList.add('hidden')
//   wineDesc.classList.add('hidden')
// })

const cusailInfo = document.getElementById("cusail-info")
const cusailCard = document.getElementById("cusail-card")
const cusailLink = document.getElementById("cusail-github-link")
const cusailLiveLink = document.getElementById("cusail-live-link")
const cusailDesc = document.getElementById("cusail-description")
cusailInfo.addEventListener('mouseover', (event) =>{
  cusailCard.classList.add('blur')
  cusailLink.classList.remove('hidden')
  cusailLiveLink.classList.remove('hidden')
  cusailDesc.classList.remove('hidden')
})
cusailInfo.addEventListener('mouseleave', (event) =>{
  cusailCard.classList.remove('blur')
  cusailLink.classList.add('hidden')
  cusailLiveLink.classList.add('hidden')
  cusailDesc.classList.add('hidden')
})

const ccInfo = document.getElementById("cc-info")
const ccCard = document.getElementById("cc-card")
const ccLink = document.getElementById("cc-github-link")
const ccLiveLink = document.getElementById("cc-live-link")
const ccDesc = document.getElementById("cc-description")
ccInfo.addEventListener('mouseover', (event) =>{
  ccCard.classList.add('blur')
  ccLink.classList.remove('hidden')
  ccLiveLink.classList.remove('hidden')
  ccDesc.classList.remove('hidden')
})
ccInfo.addEventListener('mouseleave', (event) =>{
  ccCard.classList.remove('blur')
  ccLink.classList.add('hidden')
  ccLiveLink.classList.add('hidden')
  ccDesc.classList.add('hidden')
})
